import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { cn } from "@/lib/utils"
import "@/assets/stylesheets/globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider"
import { ModalProvider } from "@/components/providers/modal-provider"
import { RealtimeProvider } from "@/components/providers/realtime-provider"
import { QueryProvider } from "@/components/providers/query-provider"
import { UserButton } from "@/components/user-button"

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="h-screen">
      <body className={cn(`${openSans.variable} antialiased font-sans`, "h-screen")}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
          storageKey="discord-theme"
        >
          <RealtimeProvider>
            <ModalProvider />
            <QueryProvider>
              {children}
            </QueryProvider>
          </RealtimeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
